import type { Metadata } from "next";
import Link from "next/link";
import getUsers from "../services/getUsers";

interface User {
  id: number;
  name: string;
}

const Page: React.FC = async () => {
  const data = await getUsers();

  return (
    <div className="container mx-auto p-4">
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        {data.map((user: User) => {
          return (
            <div
              className="card bg-white shadow-md rounded-lg p-4 flex items-center justify-center"
              key={user.id}
            >
              <Link
                href={`/users/${user.id}`}
                className="text-lg text-green-500 font-semibold"
              >
                {user.name}
              </Link>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default Page;

export const metadata: Metadata = {
  title: "user page",
  description: "Generated by create next app",
};

// import { GetServerSideProps, NextPage } from "next";

// interface User {
//   id: number;
//   name: string;
// }

// interface PageProps {
//   data: User[];
// }

// export const getServerSideProps: GetServerSideProps<PageProps> = async () => {
//   const data = await (
//     await fetch("https://jsonplaceholder.typicode.com/users")
//   ).json();
//   return { props: { data } };
// };

// const page: NextPage<PageProps> = (props) => {
//   const { data } = props;
//   return (
//     <div>
//       {data.map((user: User) => {
//         return <div key={user.id}>{user.name}</div>;
//       })}
//     </div>
//   );
// };

// export default page;
