import React from "react";
import type { Metadata } from "next";
import Counter from "../components/Counter";

const About: React.FC = () => {
  return (
    <div
      className="text-4xl text-center text-blue-500
   font-bold
   w-full"
    >
      {" "}
      <h1>my about</h1>
      <Counter />
    </div>
  );
};

export default About;
export const metadata: Metadata = {
  title: "About Page",
  description: "Generated by create next app",
};
